# Generated by Django 3.2.7 on 2021-09-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='goal',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='passs',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='subject',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='board',
            name='time',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
