# Generated by Django 3.2.7 on 2021-09-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planners', '0002_auto_20210913_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='goal',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='passs',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
